language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
install:
  - npm install
services:
  - postgresql
env:
  global:
    - NODE_ENV=test
    - JWT_SECRET=prfhdfdh
before_script:
  - psql -c "CREATE USER kifaru WITH PASSWORD null;" -U postgres
  - psql -c 'create database errorswag;' -U postgres
  - psql -U postgres -d errorswag -c 'CREATE EXTENSION pg_trgm'
  - npm run build
  - npm install -g sequelize-cli
  - sequelize db:migrate:undo:all
  - sequelize db:migrate
script:
  - npm test
after_success:
  - npm run coverage
