openapi: 3.0.0

info:
  version: "1.0"
  title: ErrorSwag
  description: "Create a community of like minded authors to foster inspiration and innovation by leveraging the modern web."

servers:
  - url: http://localhost:3000/api/v1

tags: 
  - name : "welcome"
    description: "API for quick api welcome test"
  - name : 'ratings'
    description: 'API endpoint for rating an article'
    
paths:
  /:
    get: 
      tags: 
        - welcome
      summary : Test get request
      responses:
        '200':
          description: Successfull
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response"

  /articles/{articlesId}/{ratings}:
    patch:
      tags:
        - ratings
      summary: This route enables a user to rate articles
      description: ""
      operationId: "loginUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
        - in: header
          name: x-access-token
          schema:
            type: string
            required: true
          description: This is the user id gotten from the token
        - in: path
          name: articlesId
          schema:
            type: integer
            required: true
            minimum: 1
          description: The article's id
        - in: path
          name: ratings
          schema:
            type: integer
            required: true
            minimum: 1
          description: The rating given by the user
      responses: 
        '200':
          description: Successfull
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badResponse'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badResponse'

  
components:
  
  schemas:

    response:
      type: object
      properties:
        status:
          type: string
        data:
          type: string
    badResponse:
      type: object
      properties:
        message:
          type: string

